---
title: "Anomalies and errors report"
output:
  html_document:
    code_folding: "hide"
---

```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = TRUE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 8.64,
               fig.height = 4.86,
               fig.path = 'figures/')
```

```{r}
library(dplyr)
library(bohemia)
library(leaflet)
library(ggplot2)
```

```{r}
if('data.RData' %in% dir()){
  load('data.RData')
} else {
  pd_moz <- load_odk_data(the_country = 'Mozambique',
                    credentials_path = '../../credentials/credentials.yaml',
                    users_path = '../../credentials/users.yaml')
  pd_tza <- load_odk_data(the_country = 'Tanzania',
                      credentials_path = '../../credentials/credentials.yaml',
                      users_path = '../../credentials/users.yaml')
  is_local <- FALSE
  library(DBI)
  library(RPostgres)
  source('../../rpackage/bohemia/R/app_functions.R')
  owd <- getwd()
  setwd('../../')
  con <- get_db_connection(local = is_local)
  the_country <- 'Tanzania'
  anomalies_tza <- dbGetQuery(conn = con,
                              statement = paste0("SELECT * FROM anomalies WHERE country = '", the_country, "'"))
  the_country <- 'Mozambique'
  anomalies_moz <- dbGetQuery(conn = con,
                              statement = paste0("SELECT * FROM anomalies WHERE country = '", the_country, "'"))
  corrections <- dbGetQuery(conn = con,
                            statement = "SELECT * FROM corrections;")
  fixes <- dbGetQuery(conn = con,
                            statement = "SELECT * FROM fixes;")
  dbDisconnect(conn = con)
  setwd(owd)
  save(pd_moz,
       pd_tza,
       anomalies_tza, anomalies_moz,
       corrections, fixes,
       file = 'data.RData')
}
minicensus_main <- bind_rows(
  pd_moz$minicensus_main,
  pd_tza$minicensus_main
)
minicensus_people <- bind_rows(
  pd_moz$minicensus_people,
  pd_tza$minicensus_people
)
anomalies <- bind_rows(anomalies_moz, anomalies_tza)
na_to_zero <- function(x){ifelse(is.na(x), 0, x)}
gps <- bohemia::gps
```

# Type of anomalies

```{r}
pd <- anomalies %>%
  group_by(country, description) %>%
  tally %>% arrange(country, desc(n))
View(pd)
```

# Number of anomalies

Total: 

```{r}
nrow(anomalies)
```

By country:

```{r}
anomalies %>%
  group_by(country) %>%
  tally
```

By date / country:

```{r}
anomalies %>%
  group_by(country, date) %>%
  tally %>%
  ggplot(aes(x = date, y = n, color = country)) + geom_point() + geom_line() +
  labs(x = 'Date', y = 'Anomalies') +
  theme(legend.position = 'bottom')
```

By correction status: 

```{r}
pd <- anomalies %>%
  left_join(corrections %>% dplyr::select(-instance_id)) %>%
  group_by(corrected = ifelse(!is.na(resolution_method), 'Corrected',
                              'Not yet corrected')) %>%
  tally
pd
```

By correction status and country: 

```{r}
pd <- anomalies %>%
  left_join(corrections %>% dplyr::select(-instance_id)) %>%
  group_by(country, corrected = ifelse(!is.na(resolution_method), 'Corrected',
                              'Not yet corrected')) %>%
  tally %>%
  tidyr::spread(key = corrected, value = n)
pd
```


# Number of minicensus forms 

Total:

```{r}
minicensus_main %>%
  nrow %>% knitr::kable()
```

By country:

```{r}
minicensus_main %>%
  group_by(hh_country) %>%
  tally %>% knitr::kable()
```

By date / country:

```{r}
minicensus_main %>%
  group_by(country = hh_country, date = todays_date) %>% tally %>%
    ggplot(aes(x = date, y = n, color = country)) + geom_point() + geom_line() +
  labs(x = 'Date', y = 'Minicensus forms') +
  theme(legend.position = 'bottom') +
  theme_bw()
```


By date / country (cumulative):

```{r}
minicensus_main %>%
  group_by(country = hh_country, date = todays_date) %>% tally %>%
  ungroup %>% group_by(country) %>% mutate(n = cumsum(n)) %>%
    ggplot(aes(x = date, y = n, color = country)) + geom_point() + geom_line() +
  labs(x = 'Date', y = 'Minicensus forms') +
  theme(legend.position = 'bottom') +
  theme_bw()
```

# By type

```{r}
pd <- anomalies %>%
  mutate(description = substr(description, 1, 80)) %>%
  group_by(description) %>%
  tally %>%
  arrange(desc(n)) 
pd$description <- factor(pd$description, levels = pd$description)

ggplot(data = pd,
       aes(x = description,
           y = n,
           group = 1)) +
  geom_area(fill = 'darkorange', alpha = 0.3) +
  geom_point() +
  coord_flip() +
  theme_bw() +
  labs(x = 'Ocurrences',
       y = 'Description')

```


# By type and country

```{r}
pd <- anomalies %>%
  mutate(description = substr(description, 1, 80)) %>%
  group_by(description, country) %>%
  tally %>%
  arrange(desc(n)) 
pd$description <- factor(pd$description, levels = unique(pd$description))

ggplot(data = pd,
       aes(x = description,
           y = n,
           group = country,
           color = country)) +
  geom_point() +
  geom_line(alpha = 0.5) +
  coord_flip() +
  theme_bw() +
  labs(x = 'Ocurrences',
       y = 'Description') +
  theme(legend.position = 'bottom') +
  scale_color_manual(name = '', values = c('red', 'blue'))

```

## By type and time

```{r}
pd <- anomalies %>%
  mutate(description = substr(description, 1, 80)) %>%
  group_by(description, country, month = as.Date(lubridate::floor_date(date, 'month')) + 15) %>%
  tally %>%
  arrange(desc(n)) 

types <- sort(unique(anomalies$description))

for(i in 1:length(types)){
  this_type <- types[i]
  this_data <- pd %>%
    filter(description == this_type)
  if(nrow(this_data) > 0){
      g <- ggplot(data = this_data,
              aes(x = month,
                  y = n,
                  group = country,
                  color = country)) +
    # geom_bar(stat = 'identity', position = position_dodge(width = 0.7)) +
    geom_line() +
    geom_point(size = 2, alpha = 0.7) +
    facet_wrap(~country, nrow = 1) +
      theme_bw() +
  labs(x = 'Ocurrences',
       y = 'Description',
       title = this_type) +
  theme(legend.position = 'none') +
  scale_color_manual(name = '', values = c('red', 'blue')) 
  print(g)
  print(knitr::kable(this_data %>% dplyr::select(-description)))
  }

}
```