---
title: "InterVA showcase"
author: Databrew LLC
output:
  html_document:
    code_folding: hide
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
  fig.path = "figures/",
  out.width = "100%"
)
```

```{r}
cat('Date-time: ', as.character(Sys.time()))
## Load libraries
library(ggplot2)
library(lubridate)
library(dplyr)
library(CrossVA)
library(openVA)
library(nbc4va)
library(InterVA5)
library(bohemia)
library(RPostgres)
library(tidyverse)
library(databrew)
options(scipen = '999')
ggplot2::theme_set(theme_bw())
```

```{r}
if('data.RData' %in% dir()){
  load('data.RData')
} else {
    
  is_local <- FALSE
  drv <- RPostgres::Postgres()
  # read in credenstials 
  creds <- yaml::yaml.load_file('../../credentials/credentials.yaml')
  
  if(is_local){
    con <- dbConnect(drv, dbname='bohemia')
  } else {
    psql_end_point = creds$endpoint
    psql_user = creds$psql_master_username
    psql_pass = creds$psql_master_password
    con <- dbConnect(drv, dbname='bohemia', host=psql_end_point, 
                     port=5432,
                     user=psql_user, password=psql_pass)
  }
  
  va <- dbGetQuery(conn = con,
                   'SELECT * FROM va')
  
  
  dbDisconnect(con)
  
  
  ## GET NAMES OF VARIABLES PER WHO ODK FORMAT
  # # our data (VA version 1.5.3)
  # dat <- read.csv('2016_WHO_Verbal_Autopsy_Form_1_5_3_results.csv')
  # dat <- rbind(dat, dat)
  # # https://trello.com/c/ZiqTjBeD/2328-bohemia-get-our-data-into-interva-5-format
  # # get data names
  # who_names <- tolower(unlist(lapply(strsplit(names(dat), '.',fixed = TRUE), function(x) x[length(x)])))
  who_names <- c("id10002",
  "id10003",
  "id10004",
  "id10007",
  "id10007a",
  "id10008",
  "id10009",
  "id10010",
  "id10010a",
  "id10010b",
  "id10010c",
  "id10012",
  "id10013",
  "id10011",
  "id10017",
  "id10018",
  "id10019",
  "id10020",
  "id10021",
  "id10022",
  "id10023_a",
  "id10023_b",
  "id10023",
  "id10024",
  "ageindays",
  "ageindays2",
  "ageinyears",
  "ageinyearsremain",
  "ageinmonths",
  "ageinmonthsremain",
  "isneonatal1",
  "ischild1",
  "isadult1",
  "displayageneonate",
  "displayagechild",
  "displayageadult",
  "age_group",
  "age_neonate_days",
  "age_child_unit",
  "age_child_days",
  "age_child_months",
  "age_child_years",
  "age_adult",
  "ageinmonthsbyyear",
  "ageinyears2",
  "isneonatal2",
  "ischild2",
  "isadult2",
  "isneonatal",
  "ischild",
  "isadult",
  "ageindaysneonate",
  "id10008_check",
  "id10058",
  "id10487",
  "id10488",
  "id10051",
  "id10052",
  "id10053",
  "id10054",
  "id10055",
  "id10057",
  "id10059",
  "id10060_check",
  "id10060",
  "id10061",
  "id10062",
  "id10063",
  "id10064",
  "id10065",
  "id10066",
  "id10069",
  "id10069_a",
  "id10070",
  "id10071_check",
  "id10071",
  "id10072",
  "id10073",
  "id10104",
  "id10105",
  "id10106",
  "id10107",
  "id10108",
  "id10109",
  "id10110",
  "id10111",
  "id10112",
  "id10113",
  "id10114",
  "id10115",
  "id10116",
  "id10077",
  "id10079",
  "id10080",
  "id10081",
  "id10082",
  "id10083",
  "id10084",
  "id10085",
  "id10086",
  "id10087",
  "id10088",
  "id10089",
  "id10090",
  "id10091",
  "id10092",
  "id10093",
  "id10094",
  "id10095",
  "id10096",
  "id10097",
  "id10098",
  "id10099",
  "id10100",
  "id10351",
  "id10408",
  "id10120_0",
  "id10120_unit",
  "id10121",
  "id10122",
  "id10120_1",
  "id10120",
  "id10123",
  "id10125",
  "id10126",
  "id10127",
  "id10128",
  "id10129",
  "id10130",
  "id10131",
  "id10132",
  "id10133",
  "id10134",
  "id10135",
  "id10136",
  "id10137",
  "id10138",
  "id10139",
  "id10140",
  "id10141",
  "id10142",
  "id10143",
  "id10144",
  "id10482",
  "id10483",
  "id10484",
  "id10147",
  "id10148_a",
  "id10148_units",
  "id10148_b",
  "id10148_c",
  "id10148",
  "id10149",
  "id10150",
  "id10151",
  "id10152",
  "id10153",
  "id10154_units",
  "id10154_a",
  "id10154_b",
  "id10154",
  "id10155",
  "id10156",
  "id10157",
  "id10158",
  "id10159",
  "id10161_0",
  "id10161_unit",
  "id10161_1",
  "id10162",
  "id10163",
  "id10161",
  "id10165",
  "id10166",
  "id10167_a",
  "id10167_units",
  "id10167_b",
  "id10167_c",
  "id10167",
  "id10168",
  "id10169_a",
  "id10169_units",
  "id10169_b",
  "id10169_c",
  "id10169",
  "id10170",
  "id10171",
  "id10172",
  "id10173_nc",
  "id10173_a",
  "id10173",
  "id10174",
  "id10175",
  "id10176",
  "id10178_unit",
  "id10178",
  "id10179",
  "id10179_1",
  "id10181",
  "id10182_units",
  "id10182_a",
  "id10182_b",
  "id10182",
  "id10183",
  "id10184_a",
  "id10184_units",
  "id10184_b",
  "id10184_c",
  "id10185",
  "id10186",
  "id10187",
  "id10188",
  "id10189",
  "id10190_units",
  "id10190_a",
  "id10190_b",
  "id10191",
  "id10192",
  "id10193",
  "id10194",
  "id10195",
  "id10196_unit",
  "id10196",
  "id10197_a",
  "id10198",
  "id10197",
  "id10199",
  "id10200",
  "id10201_unit",
  "id10201_a",
  "id10202",
  "id10201",
  "id10203",
  "id10204",
  "id10205_unit",
  "id10205_a",
  "id10206",
  "id10205",
  "id10207",
  "id10208",
  "id10209_units",
  "id10209_a",
  "id10209_b",
  "id10209",
  "id10210",
  "id10211_units",
  "id10211_a",
  "id10211_b",
  "id10211",
  "id10212",
  "id10213_units",
  "id10213_a",
  "id10213_b",
  "id10213",
  "id10214",
  "id10215",
  "id10216_units",
  "id10216_a",
  "id10216_b",
  "id10216",
  "id10217",
  "id10218",
  "id10219",
  "id10220",
  "id10221",
  "id10222",
  "id10223",
  "id10225",
  "id10226",
  "id10224",
  "id10227",
  "id10228",
  "id10229",
  "id10230",
  "id10231",
  "id10232_units",
  "id10232_a",
  "id10232_b",
  "id10232",
  "id10233",
  "id10234",
  "id10235",
  "id10235_check",
  "id10236",
  "id10237",
  "id10238",
  "id10239",
  "id10240",
  "id10241",
  "id10242",
  "id10243",
  "id10244",
  "id10245",
  "id10246",
  "id10247",
  "id10248_units",
  "id10248_a",
  "id10248_b",
  "id10248",
  "id10249",
  "id10250_units",
  "id10250_a",
  "id10250_b",
  "id10250",
  "id10251",
  "id10252",
  "id10253",
  "id10254",
  "id10255",
  "id10256",
  "id10257",
  "id10258",
  "id10259",
  "id10260",
  "id10260_check",
  "id10260_check2",
  "id10261",
  "id10262_units",
  "id10262_a",
  "id10262_b",
  "id10262",
  "id10263",
  "id10264",
  "id10265",
  "id10266_units",
  "id10266_a",
  "id10266_b",
  "id10266",
  "id10267",
  "id10268",
  "id10269",
  "id10270",
  "id10271",
  "id10272",
  "id10273",
  "id10274_a",
  "id10274_units",
  "id10274_b",
  "id10274_c",
  "id10274",
  "id10275",
  "id10276",
  "id10277",
  "id10278",
  "id10279",
  "id10281",
  "id10282",
  "id10283",
  "id10284",
  "id10285",
  "id10286",
  "id10287",
  "id10288",
  "id10289",
  "id10290",
  "id10485",
  "id10486",
  "id10294",
  "id10295",
  "id10296",
  "id10297",
  "id10298",
  "id10301",
  "id10299",
  "id10302",
  "id10303",
  "id10300",
  "id10304",
  "id10305",
  "id10306",
  "id10307",
  "id10308",
  "id10309",
  "id10310",
  "id10310_check",
  "id10312",
  "id10313",
  "id10314",
  "id10315_a",
  "id10315",
  "id10316",
  "id10317",
  "id10318",
  "id10319",
  "id10320",
  "id10321",
  "id10322",
  "id10323",
  "id10324",
  "id10325",
  "id10326",
  "id10327",
  "id10328",
  "id10329",
  "id10330",
  "id10331",
  "id10332",
  "id10333",
  "id10334",
  "id10335",
  "id10336",
  "id10337",
  "id10338",
  "id10339",
  "id10342",
  "id10343",
  "id10344",
  "id10347",
  "id10340",
  "id10352_units",
  "id10352_a",
  "id10352_b",
  "id10352",
  "id10354",
  "id10355",
  "id10356",
  "id10357",
  "id10358_units",
  "id10358",
  "id10359",
  "id10359_a",
  "id10360",
  "id10361",
  "id10362",
  "id10363",
  "id10364",
  "id10365",
  "id1036x_check",
  "id10366",
  "id10367",
  "id10368",
  "id10369",
  "id10370",
  "id10371",
  "id10372",
  "id10373",
  "id10394",
  "id10376",
  "id10377",
  "id10379_unit",
  "id10379",
  "id10380",
  "id10382",
  "id10383",
  "id10384",
  "id10385",
  "id10387",
  "id10388",
  "id10389",
  "id10389_check",
  "id10391",
  "id10392",
  "id10393",
  "id10395",
  "id10396",
  "id10397",
  "id10398",
  "id10399",
  "id10400",
  "id10401",
  "id10402",
  "id10403",
  "id10404",
  "id10405",
  "id10406",
  "id10411",
  "id10412",
  "id10413",
  "id10414",
  "id10414_check",
  "id10415",
  "id10416",
  "id10418",
  "id10419",
  "id10420",
  "id10421",
  "id10422",
  "id10423",
  "id10424",
  "id10425",
  "id10426",
  "id10427",
  "id10428",
  "id10429",
  "id10430",
  "id10431",
  "id10431_check",
  "id10432",
  "id10433",
  "id10433_check",
  "id10434",
  "id10435",
  "id10436",
  "id10437",
  "id10438",
  "id10439_check",
  "id10439",
  "id10440_check",
  "id10440",
  "id10441_check",
  "id10441",
  "id10442",
  "id10443",
  "id10444",
  "id10445",
  "id10446",
  "id10450",
  "id10451",
  "id10452",
  "id10453",
  "id10454",
  "id10455",
  "id10456",
  "id10457",
  "id10458",
  "id10459",
  "id10462",
  "id10463",
  "id10464",
  "id10465",
  "id10466",
  "id10467",
  "id10468",
  "id10469",
  "id10470",
  "id10471",
  "id10472",
  "id10473",
  "id10476",
  "id10477",
  "id10478",
  "id10479",
  "id10477_check",
  "id10478_check",
  "id10479_check",
  "id10481",
  "comment",
  "instanceid")
  
  
  # Get names of data per our database
  va_names <- names(va)
  
  # loop through va names and find the matching names in the WHO data and add the prefix
  
  # 36 and 39 are wet/dry and gender gor va
  for(i in 1:length(va_names)){
    this_name <- va_names[i]
    if(any(!is.na(as.numeric(va[,i])))){
      va[,i] <- as.numeric(va[,i])
    }
    if(any(grepl(this_name, who_names))){
      name_index <- which(who_names==this_name)
      # data_type <- typeof(dat[, name_index])
      # print(data_type)
      if(is.integer(dat[, name_index])){
        va[,i] <- as.integer(va[,i])
      } else if(is.logical(dat[, name_index])){
        va[,i] <- as.logical(va[,i])
      } else if(is.character(dat[, name_index])){
        va[,i] <- as.character(va[,i])
      } else if(is.factor(dat[, name_index])) {
        va[,i] <- as.factor(va[,i])
      }
      names(va)[i] <- names(dat)[name_index]
      print(i)
    }
  }
  # temp_who <- odk2openVA_v151(dat, id_col = 'meta.instanceID')
  temp_va <- odk2openVA_v151(va, id_col = 'death_id')
  out <- InterVA5(temp_va,  HIV = "h", Malaria = "h", directory = getwd())
  
  # Get into dataframe format
  out_list <- list()
  individual <- out$VA5
  for(i in 1:length(individual)){
    this_individual <- individual[[i]]
    id <- this_individual$ID
    x <- summary(out, id = cause1)
    probs <- x$probs
    vals <- as.numeric(probs)
    the_names <- names(probs)  
    df <- tibble(ID = id,
                 COD = the_names,
                 Probability = vals)
    out_list[[i]] <- df
  }
  df <- bind_rows(out_list)
  
  save(out, df, file = 'data.RData')
}
```

# Overall results

Below are top results for all `r length(unique(df$ID))` deaths:

```{r}
print(summary(out))
```


```{r, eval = FALSE}
# Below are population-level summed probabilities

pd <- df %>%
  group_by(COD) %>%
  summarise(Probability = sum(Probability)) %>%
  arrange(desc(Probability))
pd$COD <- factor(pd$COD, levels = pd$COD)
  ggplot(data = pd,
         aes(x = COD,
             y = Probability)) +
    geom_bar(stat = 'identity') +
    theme(axis.text.x = element_text(angle = 90,
                                     vjust = 0.5,
                                     hjust = 1))
```

# Person-specific results


Below is the format of probabilities for _one random death_:

```{r}
options(scipen = '999')
pd <- df %>%
  filter(ID == dplyr::first(ID)) %>%
  mutate(ID = '<CENSORED>') %>%
  arrange(desc(Probability))
databrew::prettify(pd, 
                   nrows = nrow(pd),
                   round_digits = 10)
```

