#' Format VA Refusals
#' 
#' Take the VA Refusals data (as generated by "odk_get_data") and format it so it's ready for popping into the database
#' @param data The list of dataframes (non_repeats and repeats) generated by odk_get_data
#' @param keyfile The public key file to be used for encryption
#' @return A list of dataframes formatted and named in accordance with the bohemia database
#' @import dplyr
#' @export

format_va_refusals <- function(data, keyfile){
  
  df <- data$non_repeats

  df <- df %>%
    dplyr::select(instance_id = instanceID,
                  todays_date,
                  death_id,
                  start_time,
                  end_time,
                  have_wid,
                  wid_manual,
                  wid_qr,
                  wid,
                  reason_no_participate,
                  server
                  )
 
  
  
  # Return the formatted data
  out <- list(df)
  names(out) <- c('va_refusals')
  # Clean up uuid column
  for(i in 1:length(out)){
    if(!is.null(out[[i]])){
      if('instance_id' %in% names(out[[i]])){
        out[[i]]$instance_id <- gsub('uuid:', '', out[[i]]$instance_id)
      }
    }
  }
  return(out)
}