---
title: "ICF tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(gsheet)
library(DT)
library(shiny)
```

```{r}
# Get fieldworker data
  # Define a default fieldworkers data
  if(!'fids.csv' %in% dir('/tmp')){
    fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=0'
    fids1 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor, Role = details) %>% dplyr::mutate(country = 'Tanzania')
    fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=409816186'
    fids2 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor, Role = details) %>% dplyr::mutate(country = 'Mozambique')
    fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=179257508'
    fids3 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor, Role = details) %>% dplyr::mutate(country = 'Catalonia')
    fids <- bind_rows(fids1, fids2, fids3)
    readr::write_csv(fids, '/tmp/fids.csv')
  } else {
    fids <- readr::read_csv('/tmp/fids.csv')
  }

# Read in locations
locations <- bohemia::locations
  


# Prepare some dummy data
date_choices <- as.Date((Sys.Date()-30):Sys.Date(), origin = '1970-01-01')
dates <- sample(date_choices, 1500, replace = TRUE)
hh_ids <- paste0(sample(locations$code, 1500, replace = T), '-',
                 seq(100, 599, by = 1))
hh <- 
  tibble(date = dates,
         hh_id = hh_ids)
out_list <- list()
for(i in 1:nrow(hh)){
  this_hh <- hh$hh_id[i]
  nn <- sample(1:15, 1)
  nums <- bohemia::add_zero(1:nn, 3)
  ids <- paste0(this_hh, '-', nums)
  out <- tibble(hh_id = this_hh,
                date = hh$date[i],
                id = ids)
  out_list[[i]] <- out
}
df <- bind_rows(out_list)
df$fid <- sample(fids$bohemia_id[!is.na(fids$first_name)], nrow(df), replace = TRUE)
df <- left_join(df, fids %>% mutate(fw_name = paste0(first_name, ' ', last_name)) %>%
                                      dplyr::select(bohemia_id, fw_name), by = c('fid' = 'bohemia_id'))
df$hamlet_code <- substr(df$id, 1, 3)
df <- left_join(df, locations %>% dplyr::select(code, hamlet = Hamlet), by = c('hamlet_code' = 'code'))
df$name <- paste0(sample(babynames::babynames$name, nrow(df), replace = TRUE))
df$age <- rnorm(n = nrow(df), mean = 50, sd = 20); df$age <- ifelse(df$age <0, df$age *-1, df$age)
df$type_icf <- sample(c('HoH',
                        'Adult',
                        'Child 12-18',
                        'Parent/guardian'),
                      nrow(df),
                      replace = TRUE)
df$pid <- df$id
```


# Intro {.sidebar}

This tool is meant for use by archivists working on tablets and/or computers at headquarters.

# ICF First Verification

## Column 1

### Date selection

```{r}
dateInput('date_of_visit', 'Date of visit',min = min(df$date),
          max = max(df$date))
```

### Household selection


```{r}
renderUI({
  date_of_visit <- input$date_of_visit
  if(is.null(date_of_visit)){
    NULL
  } else {
    choices <- df %>% filter(date == date_of_visit) 
    the_choices <- sort(unique(choices$hh_id))
    selectInput('hh_id', 'Household ID', choices = the_choices)
  }
})
```

```{r}
dfr <- reactive({
  out <- df
  date_of_visit <- input$date_of_visit
  xhid <- input$hh_id
  person_id <- input$person_id
  if(!is.null(date_of_visit)){
    out <- out %>% filter(date == date_of_visit)
  }
  if(!is.null(xhid)){
    out <- out %>% filter(hh_id == xhid)
  }
  if(!is.null(person_id)){
    out <- out %>% filter(pid == person_id)
  }
  return(out)
})
```

### Person selection

```{r}
renderUI({
  out <- df
  out <- data.frame(out)
  date_of_visit <- input$date_of_visit
  xhid <- input$hh_id
  done <- NULL
  if(!is.null(date_of_visit)){
    if(!is.null(xhid)){
      out <- out %>% 
        filter(date == date_of_visit) %>%
        filter(hh_id == xhid)
      id_choices <- out$pid
      done <- selectInput('person_id', 'Person ID', choices = id_choices)
    }
  }
  return(done)
})

```





## Column 2

### Person details

```{r}
DT::renderDataTable({
    
})

```

### Data input

```{r}
selectInput('present', 'Is the ICF present?',
            choices = c('Yes', 'No'))
```

### Errors transcription

```{r}
renderUI({
  present <- input$present
  out <- NULL
  if(!is.null(out)){
    if(present){
    fluidPage(
      p('Check the "Verification list for supervisors". Did the ICF present any of the following errors detected by the supervisor in the field?'),
      checkboxGroupInput('errors', 'Select all that apply',
                         choices = c('Participant did not sign',
                                     'Participant did not date',
                                     'Witness did not sign',
                                     'Witness did not date',
                                     'Fieldworker did not sign',
                                     'Fieldworker did not date',
                                     'Dates do not match',
                                     'Fieldworker wrote participant name',
                                     'Fieldworker wrote participant date',
                                     'Fieldworker wrote witness name',
                                     'Fieldworker wrote witness date',
                                     'Unclear thumbprint',
                                     'No errors'))
    )
    }
  }
  
})
```